akka {
     loglevel = "DEBUG"
  actor {
    provider = "remote"
    allow-java-serialization = on
  }
  remote {
    use-unsafe-remote-features-outside-cluster = on
    artery {
      transport = tcp
      canonical.hostname = "127.0.0.1"
      canonical.port = 9090
    }
  }
}

number-sources=7
number-reducers=4
source-1="Great Expectations|https://raw.githubusercontent.com/pablo-desperados/dickens_text/refs/heads/main/Great%20Expectations.txt"
source-2="Little Stories|https://raw.githubusercontent.com/pablo-desperados/dickens_text/refs/heads/main/Little%20Stories.txt"
source-3="The Call of Cthulhu|https://raw.githubusercontent.com/pablo-desperados/dickens_text/refs/heads/main/The%20Call%20of%20Cthulhu.txt"
source-4="Christmas Carol|https://raw.githubusercontent.com/pablo-desperados/dickens_text/refs/heads/main/Christmas%20Carol.txt"
source-5="The Raven|https://raw.githubusercontent.com/pablo-desperados/dickens_text/refs/heads/main/The%20Raven.txt"
source-6="A Man of Business|https://raw.githubusercontent.com/rcdm-uga/Gutenberg_Text/refs/heads/master/Balzac%2C%20Honor%C3%A9%20de/A%20Man%20of%20Business.txt"
source-7="A Child's Dream of a Star|https://raw.githubusercontent.com/rcdm-uga/Gutenberg_Text/refs/heads/master/Dickens%2C%20Charles/A%20Child's%20Dream%20of%20a%20Star.txt"