akka {
     loglevel = "DEBUG"
  actor {
    provider = "remote"
    allow-java-serialization = on
  }
  remote {
    use-unsafe-remote-features-outside-cluster = on
    artery {
      transport = tcp
      canonical.hostname = "127.0.0.1"
      canonical.port = 9090
    }
  }
}

number-sources=7
number-reducers=4
source-1="Great Expectations|https://www.gutenberg.org/cache/epub/24022/pg24022.txt"
source-2="Little Dorrit|https://www.gutenberg.org/cache/epub/963/pg963.txt"
source-3="David Copperfield|https://www.gutenberg.org/cache/epub/766/pg766.txt"
source-4="Christmas Carol|https://www.gutenberg.org/cache/epub/24022/pg24022.txt"
source-5="Nicholas Nickleby|https://www.gutenberg.org/cache/epub/967/pg967.txt"
source-6="The Old Curiosity Shop|https://www.gutenberg.org/cache/epub/700/pg700.txt"
source-7="Dombey and Son|https://www.gutenberg.org/cache/epub/821/pg821.txt"