include "application.conf"

akka.remote.artery.canonical.port = 2551
akka.actor.deployment {
  /mapRouter {
    router = round-robin-pool
    instances = 4
    remote = ["akka://RemoteSystem@127.0.0.1:2552", "akka://RemoteSystem@127.0.0.1:2553"]
  }
  /reduceRouter {
    router = consistent-hashing-pool
    nstances = 4
    remote = ["akka://RemoteSystem@127.0.0.1:2552", "akka://RemoteSystem@127.0.0.1:2553"]
  }
}